name: Web in AKS

# Deploy the Tailwind Traders Web as a deployment in a EXISTING AKS THAT ALREADY HAS THE BACKEND INSTALLED
#
# Note: The AKS MUST HAVE TLS INSTALLED 
# Please refer to https://github.com/Microsoft/TailwindTraders-Backend#enabling-ssltls-on-the-cluster-optional-but-highly-recommended and following. 
# Installing the WEB on AKS without TLS enabled is NOT supported.

on:
  push:
    branches:
      - master

jobs:
  buildpush:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Docker build and push
      working-directory: Source/Tailwind.Traders.Web
      run: | 
        docker build . --build-arg sdkTag=2.1 --build-arg runtimeTag=2.1 -t tailwindtraders/web:gh-${{ github.sha }} -t latest
        docker push tailwindtraders/web:gh-${{ github.sha }}

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Set AKS kubectl context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
        resource-group: ${{ secrets.AKS_RESOURCEGROUP_NAME }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh
        export PATH=/usr/local/bin/helm

    - name: Install Helm Chart
      run: |
        helm upgrade --install tailwindtraders-web ./Deploy/helm/web -f ./Deploy/helm/gvalues.yaml -f ./Deploy/helm/values.b2c.yaml  --set ingress.hosts={${{ secrets.AKS_HOST_NAME }}}  --set ingress.protocol=https --set ingress.tls[0].hosts={${{ secrets.AKS_HOST_NAME }}}  --set ingress.tls[0].secretName=${{ secrets.AKS_TLS_SECRET_NAME }} --set image.repository=tailwindtraders/web --set image.tag=gh-${{ github.sha }}
